runfile('/home/vgs23/Constrained_dynamics.py', wdir='/home/vgs23')
runfile('/home/vgs23/MD_Simulation.py', wdir='/home/vgs23')
runfile('/home/vgs23/MD_Simulation.py', wdir='/home/vgs23')
runfile('/home/vgs23/Constrained_dynamics.py', wdir='/home/vgs23')
runfile('/home/vgs23/MD_Simulation.py', wdir='/home/vgs23')
runfile('/home/vgs23/Correlation_function.py', wdir='/home/vgs23')
runfile('/home/vgs23/MD_Simulation.py', wdir='/home/vgs23')
runfile('/home/vgs23/Constrained_dynamics.py', wdir='/home/vgs23')
runfile('/home/vgs23/Correlation_function.py', wdir='/home/vgs23')
runfile('/home/vgs23/MD_Simulation.py', wdir='/home/vgs23')
runfile('/home/vgs23/Constrained_dynamics.py', wdir='/home/vgs23')
runfile('/home/vgs23/Constrained_dynamics.py', wdir='/home/vgs23')
runfile('/home/vgs23/MD_Simulation.py', wdir='/home/vgs23')
runfile('/home/vgs23/MD_Simulation.py', wdir='/home/vgs23')
runfile('/home/vgs23/Constrained_dynamics.py', wdir='/home/vgs23')
runfile('/home/vgs23/MD_Simulation.py', wdir='/home/vgs23')
runfile('/home/vgs23/Velocity_verlet.py', wdir='/home/vgs23')
runfile('/home/vgs23/MD_Simulation.py', wdir='/home/vgs23')
runfile('/home/vgs23/MD_Simulation.py', wdir='/home/vgs23')
runfile('/home/vgs23/MD_Simulation.py', wdir='/home/vgs23')
runfile('/home/vgs23/Constrained_dynamics.py', wdir='/home/vgs23')
runfile('/home/vgs23/MD_Simulation.py', wdir='/home/vgs23')

## ---(Fri Jan 24 11:39:10 2020)---
runfile('/home/vgs23/Constrained_dynamics.py', wdir='/home/vgs23')
runfile('/home/vgs23/MD_Simulation.py', wdir='/home/vgs23')
runfile('/home/vgs23/Constrained_dynamics.py', wdir='/home/vgs23')
runfile('/home/vgs23/MD_Simulation.py', wdir='/home/vgs23')
runfile('/home/vgs23/Correlation_function.py', wdir='/home/vgs23')
runfile('/home/vgs23/MD_Simulation.py', wdir='/home/vgs23')
runfile('/home/vgs23/Correlation_function.py', wdir='/home/vgs23')
runfile('/home/vgs23/MD_Simulation.py', wdir='/home/vgs23')
runfile('/home/vgs23/Correlation_function.py', wdir='/home/vgs23')
runfile('/home/vgs23/MD_Simulation.py', wdir='/home/vgs23')
runfile('/home/vgs23/Langevin_thermostat.py', wdir='/home/vgs23')
runfile('/home/vgs23/MD_Simulation.py', wdir='/home/vgs23')
runfile('/home/vgs23/Correlation_function.py', wdir='/home/vgs23')
runfile('/home/vgs23/MD_Simulation.py', wdir='/home/vgs23')
runfile('/home/vgs23/MD_Simulation.py', wdir='/home/vgs23')
runfile('/home/vgs23/Correlation_function.py', wdir='/home/vgs23')
runfile('/home/vgs23/MD_Simulation.py', wdir='/home/vgs23')
runfile('/home/vgs23/MD_Simulation.py', wdir='/home/vgs23')
runfile('/home/vgs23/MD_Simulation.py', wdir='/home/vgs23')
runfile('/home/vgs23/MD_Simulation.py', wdir='/home/vgs23')
runfile('/home/vgs23/MD_Simulation.py', wdir='/home/vgs23')
runfile('/home/vgs23/f2pysample.py', wdir='/home/vgs23')
import numpy
import fib1
print(fib1.fib.__doc__)


a  = numpy.zeros(8,'d')
fib1.fib(a)
print(a)
runfile('/home/vgs23/MD_Simulation.py', wdir='/home/vgs23')
runfile('/home/vgs23/Quantum_tcf.py', wdir='/home/vgs23')
runfile('/home/vgs23/Quantum_tcf.py', wdir='/home/vgs23')
runfile('/home/vgs23/Quantum_tcf.py', wdir='/home/vgs23')
runfile('/home/vgs23/Quantum_tcf.py', wdir='/home/vgs23')
runfile('/home/vgs23/Quantum_tcf.py', wdir='/home/vgs23')
runfile('/home/vgs23/Quantum_tcf.py', wdir='/home/vgs23')
runfile('/home/vgs23/Quantum_tcf.py', wdir='/home/vgs23')
runfile('/home/vgs23/Quantum_tcf.py', wdir='/home/vgs23')

## ---(Fri Feb 14 10:52:55 2020)---
runfile('/home/vgs23/Python_files/MD_Simulation.py', wdir='/home/vgs23/Python_files')
runfile('/home/vgs23/Python_files/MD_Simulation.py', wdir='/home/vgs23/Python_files')
runfile('/home/vgs23/Python_files/MD_Simulation.py', wdir='/home/vgs23/Python_files')
runfile('/home/vgs23/Python_files/Quasicentroid_dynamics.py', wdir='/home/vgs23/Python_files')
runfile('/home/vgs23/Python_files/MD_Simulation.py', wdir='/home/vgs23/Python_files')
runfile('/home/vgs23/Python_files/Quasicentroid_dynamics.py', wdir='/home/vgs23/Python_files')
runfile('/home/vgs23/Python_files/MD_Simulation.py', wdir='/home/vgs23/Python_files')
runfile('/home/vgs23/Python_files/Quasicentroid_dynamics.py', wdir='/home/vgs23/Python_files')
runfile('/home/vgs23/Python_files/MD_Simulation.py', wdir='/home/vgs23/Python_files')
runfile('/home/vgs23/Python_files/OTOC/Quantum_tcf.py', wdir='/home/vgs23/Python_files/OTOC')
runfile('/home/vgs23/Python_files/Quasicentroid_dynamics.py', wdir='/home/vgs23/Python_files')
runfile('/home/vgs23/Python_files/MD_Simulation.py', wdir='/home/vgs23/Python_files')

## ---(Mon Feb 17 13:28:32 2020)---
runfile('/home/vgs23/Python_files/MD_Simulation.py', wdir='/home/vgs23/Python_files')
runfile('/home/vgs23/Python_files/MD_Simulation.py', wdir='/home/vgs23/Python_files')
runfile('/home/vgs23/Python_files/sample.py', wdir='/home/vgs23/Python_files')
runfile('/home/vgs23/Python_files/OTOC/Quantum_tcf.py', wdir='/home/vgs23/Python_files/OTOC')
runfile('/home/vgs23/Python_files/MD_Simulation.py', wdir='/home/vgs23/Python_files')
runfile('/home/vgs23/Python_files/Correlation_function.py', wdir='/home/vgs23/Python_files')
runfile('/home/vgs23/Python_files/MD_Simulation.py', wdir='/home/vgs23/Python_files')
runfile('/home/vgs23/Python_files/MD_Simulation.py', wdir='/home/vgs23/Python_files')
runfile('/home/vgs23/Python_files/MD_Simulation.py', wdir='/home/vgs23/Python_files')
runfile('/home/vgs23/Python_files/MD_Simulation.py', wdir='/home/vgs23/Python_files')
runfile('/home/vgs23/Python_files/MD_Simulation.py', wdir='/home/vgs23/Python_files')
runfile('/home/vgs23/Python_files/Correlation_function.py', wdir='/home/vgs23/Python_files')
runfile('/home/vgs23/Python_files/MD_Simulation.py', wdir='/home/vgs23/Python_files')
runfile('/home/vgs23/Python_files/OTOC/Quantum_tcf.py', wdir='/home/vgs23/Python_files/OTOC')
runfile('/home/vgs23/Python_files/Potentials_1D.py', wdir='/home/vgs23/Python_files')
runfile('/home/vgs23/Python_files/OTOC/Quantum_tcf.py', wdir='/home/vgs23/Python_files/OTOC')
runfile('/home/vgs23/Python_files/MD_Simulation.py', wdir='/home/vgs23/Python_files')
runfile('/home/vgs23/Python_files/OTOC/Quantum_tcf.py', wdir='/home/vgs23/Python_files/OTOC')

## ---(Tue Feb 25 12:03:40 2020)---
runfile('/home/vgs23/Python_files/OTOC/Quantum_tcf.py', wdir='/home/vgs23/Python_files/OTOC')
runfile('/home/vgs23/George\'s results/qclpysim-feat-v02.1/examples/simulations/qtip4pf/300K_128mol/trpmd/300K_128mol_trpmd.py', wdir='/home/vgs23/George\'s results/qclpysim-feat-v02.1/examples/simulations/qtip4pf/300K_128mol/trpmd')

## ---(Wed Feb 26 15:36:27 2020)---
runfile('/home/vgs23/qclpysim-feat-v02.1/examples/simulations/qtip4pf/300K_128mol/trpmd/300K_128mol_trpmd.py', wdir='/home/vgs23/qclpysim-feat-v02.1/examples/simulations/qtip4pf/300K_128mol/trpmd')
runfile('/home/vgs23/qclpysim-feat-v02.1/examples/simulations/qtip4pf/300K_128mol/qcmd/300K_128mol_qcmd.py', wdir='/home/vgs23/qclpysim-feat-v02.1/examples/simulations/qtip4pf/300K_128mol/qcmd')
runfile('/home/vgs23/Python_files/OTOC/OTOC.py', wdir='/home/vgs23/Python_files/OTOC')
runfile('/home/vgs23/Python_files/OTOC/Quantum_tcf.py', wdir='/home/vgs23/Python_files/OTOC')
runfile('/home/vgs23/Python_files/OTOC/Quantum_tcf.py', wdir='/home/vgs23/Python_files/OTOC')
runfile('/home/vgs23/qclpysim-feat-v02.1/qclpysim/utils/tcfs.py', wdir='/home/vgs23/qclpysim-feat-v02.1/qclpysim/utils')
0.1/137*1.89e8
runfile('/home/vgs23/Python_files/OTOC/force_field.py', wdir='/home/vgs23/Python_files/OTOC')